# Generated by Django 4.2.6 on 2025-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrow',
            name='back_time',
            field=models.DateTimeField(auto_now=True, verbose_name='归还日期'),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='borrow_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借阅时间'),
        ),
    ]
