# Generated by Django 4.2.6 on 2025-02-03 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_bookborrow_back_time_alter_bookborrow_borrow_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(verbose_name='评分')),
                ('rate_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rate_object', to='book.book', verbose_name='评分图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rate_user', to=settings.AUTH_USER_MODEL, verbose_name='评分用户')),
            ],
            options={
                'verbose_name': '用户评分',
                'verbose_name_plural': '用户评分',
            },
        ),
    ]
